# Generated by Django 6.0.1 on 2026-02-09 11:43

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Cash Register',
                'verbose_name_plural': 'Cash Registers',
                'db_table': 'cash_register_register',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CashRegisterSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('enable_cash_register', models.BooleanField(default=True, verbose_name='Enable Cash Register')),
                ('require_opening_balance', models.BooleanField(default=False, help_text='Require manual cash count when opening a session.', verbose_name='Require Opening Balance')),
                ('require_closing_balance', models.BooleanField(default=True, help_text='Require manual cash count when closing a session.', verbose_name='Require Closing Balance')),
                ('allow_negative_balance', models.BooleanField(default=False, verbose_name='Allow Negative Balance')),
                ('auto_open_session_on_login', models.BooleanField(default=True, help_text='Automatically open a cash session when user logs in.', verbose_name='Auto Open on Login')),
                ('auto_close_session_on_logout', models.BooleanField(default=True, help_text='Automatically close session when user logs out.', verbose_name='Auto Close on Logout')),
                ('protected_pos_url', models.CharField(blank=True, default='/modules/sales/pos/', help_text='URL that requires an open cash session.', max_length=200, verbose_name='Protected POS URL')),
            ],
            options={
                'verbose_name': 'Cash Register Settings',
                'verbose_name_plural': 'Cash Register Settings',
                'db_table': 'cash_register_settings',
                'abstract': False,
                'unique_together': {('hub_id',)},
            },
        ),
        migrations.CreateModel(
            name='CashSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('session_number', models.CharField(db_index=True, max_length=50, verbose_name='Session Number')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('suspended', 'Suspended')], default='open', max_length=20, verbose_name='Status')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='Opened At')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Opening Balance')),
                ('opening_notes', models.TextField(blank=True, default='', verbose_name='Opening Notes')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Closed At')),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Closing Balance')),
                ('expected_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Expected Balance')),
                ('difference', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Difference')),
                ('closing_notes', models.TextField(blank=True, default='', verbose_name='Closing Notes')),
                ('register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='cash_register.cashregister', verbose_name='Register')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_sessions', to='accounts.localuser', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Cash Session',
                'verbose_name_plural': 'Cash Sessions',
                'db_table': 'cash_register_session',
                'ordering': ['-opened_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('movement_type', models.CharField(choices=[('sale', 'Sale'), ('refund', 'Refund'), ('in', 'Cash In'), ('out', 'Cash Out')], max_length=20, verbose_name='Type')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive for in/sale, negative for out/refund.', max_digits=12, verbose_name='Amount')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('transfer', 'Transfer'), ('other', 'Other')], default='cash', max_length=20, verbose_name='Payment Method')),
                ('sale_reference', models.CharField(blank=True, default='', max_length=100, verbose_name='Sale Reference')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements', to='accounts.localuser', verbose_name='Employee')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='cash_register.cashsession', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Cash Movement',
                'verbose_name_plural': 'Cash Movements',
                'db_table': 'cash_register_movement',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CashCount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('count_type', models.CharField(choices=[('opening', 'Opening Count'), ('closing', 'Closing Count')], max_length=20, verbose_name='Count Type')),
                ('denominations', models.JSONField(default=dict, help_text='{"bills": {"50": 2, "20": 5}, "coins": {"2": 10, "1": 20}}', verbose_name='Denominations')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('counted_at', models.DateTimeField(auto_now_add=True, verbose_name='Counted At')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counts', to='cash_register.cashsession', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Cash Count',
                'verbose_name_plural': 'Cash Counts',
                'db_table': 'cash_register_count',
                'ordering': ['-counted_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='cashsession',
            index=models.Index(fields=['user', 'status'], name='cash_regist_user_id_518e86_idx'),
        ),
        migrations.AddIndex(
            model_name='cashsession',
            index=models.Index(fields=['status', 'opened_at'], name='cash_regist_status_b28288_idx'),
        ),
        migrations.AddIndex(
            model_name='cashmovement',
            index=models.Index(fields=['session', 'movement_type'], name='cash_regist_session_f2f9c8_idx'),
        ),
        migrations.AddIndex(
            model_name='cashmovement',
            index=models.Index(fields=['sale_reference'], name='cash_regist_sale_re_693050_idx'),
        ),
    ]
