# Generated by Django 5.2.8 on 2025-11-24 00:30

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegisterConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enable_cash_register', models.BooleanField(default=True, help_text='Enable/disable cash register functionality')),
                ('require_opening_balance', models.BooleanField(default=False, help_text='Require manual cash count when user logs in (if False, uses previous closing balance)')),
                ('require_closing_balance', models.BooleanField(default=True, help_text='Require manual cash count when user logs out')),
                ('allow_negative_balance', models.BooleanField(default=False, help_text='Allow cash balance to go negative')),
                ('auto_open_session_on_login', models.BooleanField(default=True, help_text='Automatically open cash session when user logs in')),
                ('auto_close_session_on_logout', models.BooleanField(default=True, help_text='Automatically close cash session when user logs out')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cash Register Configuration',
                'verbose_name_plural': 'Cash Register Configuration',
                'db_table': 'cash_register_config',
            },
        ),
        migrations.CreateModel(
            name='CashSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_number', models.CharField(help_text='Auto-generated session number', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cash in register at session opening', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('opening_notes', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=2, help_text='Cash in register at session closing', max_digits=10, null=True)),
                ('expected_balance', models.DecimalField(blank=True, decimal_places=2, help_text='Expected balance based on movements', max_digits=10, null=True)),
                ('difference', models.DecimalField(blank=True, decimal_places=2, help_text='Difference between expected and actual closing balance', max_digits=10, null=True)),
                ('closing_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who owns this session', on_delete=django.db.models.deletion.CASCADE, related_name='cash_sessions', to='accounts.localuser')),
            ],
            options={
                'db_table': 'cash_register_session',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('sale', 'Sale'), ('in', 'Cash In'), ('out', 'Cash Out')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount (positive for in/sale, negative for out)', max_digits=10)),
                ('sale_reference', models.CharField(blank=True, help_text='Sale number if movement is from a sale', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the movement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='cash_register.cashsession')),
            ],
            options={
                'db_table': 'cash_register_movement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashCount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('count_type', models.CharField(choices=[('opening', 'Opening Count'), ('closing', 'Closing Count')], max_length=20)),
                ('denominations', models.JSONField(default=dict, help_text='Cash count by denomination')),
                ('total', models.DecimalField(decimal_places=2, help_text='Total counted', max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('counted_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counts', to='cash_register.cashsession')),
            ],
            options={
                'db_table': 'cash_register_count',
                'ordering': ['-counted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cashsession',
            index=models.Index(fields=['user', 'status'], name='cash_regist_user_id_518e86_idx'),
        ),
        migrations.AddIndex(
            model_name='cashsession',
            index=models.Index(fields=['status', 'opened_at'], name='cash_regist_status_b28288_idx'),
        ),
        migrations.AddIndex(
            model_name='cashmovement',
            index=models.Index(fields=['session', 'movement_type'], name='cash_regist_session_f2f9c8_idx'),
        ),
        migrations.AddIndex(
            model_name='cashmovement',
            index=models.Index(fields=['sale_reference'], name='cash_regist_sale_re_693050_idx'),
        ),
    ]
