# Generated by Django 5.2.8 on 2025-11-24 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashregisterconfig',
            name='protected_pos_url',
            field=models.CharField(blank=True, default='/plugins/sales/pos/', help_text='URL that requires open cash session (default: /plugins/sales/pos/)', max_length=200),
        ),
    ]
